"""add artist name in music table

Revision ID: a71e15ab4ecb
Revises: ade69aec4757
Create Date: 2025-02-12 21:35:39.110523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71e15ab4ecb'
down_revision = 'ade69aec4757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('song', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musics')
    # ### end Alembic commands ###
